tof_camera:
  node_name: tof_camera_node
  namespace: tof
  frame_id: tof_link
  serial_number: "303000c"
  vertical_flip: false  # Camera mounted upright: node applies 180° correction

optical_head:
  node_name: optical_head_node
  namespace: optical_head
  frame_id: optical_head_link
  serial_port: "/dev/ttyACM0"
  # serial_port: "/dev/pgv100"

lidar_front:
  node_name: sllidar_front
  namespace: lidar_front
  serial_port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_6ddeb21a642a9c48be07ae66e837a4df-if00-port0"
  serial_baudrate: 256000
  frame_id: lidar_front_link
  scan_mode: "Sensitivity"

lidar_rear:
  node_name: sllidar_rear
  namespace: lidar_rear
  serial_port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_a4e887758722a544970fdf170f4b6bb6-if00-port0"
  serial_baudrate: 256000
  frame_id: lidar_rear_link
  scan_mode: "Sensitivity"
