std_msgs/Header header
float32 angle               # degree
float32 x_pos              # millimeter
float32 y_pos              # millimeter
string direction           # direction string
int32 color_lane_count     # number of color lanes
uint8 no_color_lane         # no color lane detected
uint8 no_pos                # no position detected
uint8 tag_detected          # tag detected
string warning_string
bool error
int32 tag_id