scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: robot_footprint_box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_footprint
        min_x: -0.696
        max_x: 0.696
        min_y: -0.6225
        max_y: 0.6225
        min_z: -0.05
        max_z: 0.30
        invert: false